[package]
name = "dot-viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dot-parser = "0.1.3"
#dot-parser = { git = "https://framagit.org/Bromind/dot-parser.git" }
repl-rs = "0.2.6"
